### ISSUE TITLE
Missing function (delete_clip): How to call?

### ISSUE THREAD

**Issue by Andonvr** [ricardomatias/ableton-live#22]
I think there's a function definition missing in the `Tracks` class: delete_clip.  
So I was wondering if I could call it myself. The .call function on the Tracks-object is protected, and if I want to use the .call function on the AbletonLive-object, I need the track's path, which is also protected.
Is there another way to do this? There are other functions that aren't defined in this package either, so a way to call them "by hand" would be great.

**Comment by ricardomatias** [comment]
The "delete_clip" function is part of a class of functions which are more complicated to address due to the fact that they require an instance of an element which is to be used as an argument. Case in point, to use delete_clip we must provide a clip, but at the moment this library doesn't have a way to address this.

**Comment by ricardomatias** [comment]
It's now part of the latest release of v0.0.10
